service: workstreams

provider:
  name: aws
  runtime: nodejs14.x
  tracing:
    lambda: true
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  environment:

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    target: "node14"
    concurrency: 10
    bundle: true
    minify: false
    external:
      - "node:*"

package:
  excludeDevDependencies: true
  individually: true

functions:
  - ${file(sls/functions/createAlbum.yml)}
  - ${file(sls/functions/listAlbuns.yml)}
  - ${file(sls/functions/authorizerFunc.yml)}
  - ${file(sls/functions/getToken.yml)}

resources:
